### projector_r
PUT http://localhost:5000/projector_r/blob_brightness

0.1

### projector_g
PUT http://localhost:5000/projector_g/blob_brightness

0.1

### projector_b
PUT http://localhost:5000/projector_b/blob_brightness

0.1

### camera
POST http://localhost:5000/camera/start_streaming

{
  "main_resolution": [
    820,
    616
  ],
  "buffer_count": 1
}

### camera
POST http://localhost:5000/camera/set_shutter

{
    "shutter_on": true
}

### camera
PUT http://localhost:5000/camera/objective

4

### camera
PUT http://localhost:5000/camera/exposure_gain

11




### stage
POST http://localhost:5000/stage/set_zero_position

{
}

### stage
POST http://localhost:5000/stage/set_zero_position

{
}

### stage
POST http://localhost:5000/stage/set_zero_position

{
}

### stage
POST http://localhost:5000/stage/get_pos

{}

### stage
POST http://localhost:5000/stage/jp

{}

### stage
POST http://localhost:5000/stage/jn

{}

### stage
POST http://localhost:5000/stage/move_relative

{
  "x": 0,
  "y": 400,
  "z": 0
}

### stage
POST http://localhost:5000/stage/move_absolute

{
  "x": 0,
  "y": 0,
  "z": 0
}

### stage
GET http://localhost:5000/stage/position

### stage
GET http://localhost:5000/stage/speed

### stage
PUT http://localhost:5000/stage/speed

0.5

### stage
GET http://localhost:5000/stage/tick_interval

### stage
PUT http://localhost:5000/stage/tick_interval

0.002


### My
POST http://localhost:5000/my/start_ws

### My
POST http://localhost:5000/my/end_ws

### My conn
POST http://localhost:5000/my/conn
Accept: application/json
Content-Type: application/json

{}

### My info
POST http://localhost:5000/my/info
Accept: application/json
Content-Type: application/json

{}

### My G28
POST http://localhost:5000/my/g28
Accept: application/json
Content-Type: application/json

{}

### M84
POST http://localhost:5000/my/m84
Accept: application/json
Content-Type: application/json

{}

### Z pos
POST http://localhost:5000/my/z_pos
Accept: application/json
Content-Type: application/json

{
  "z_pos": 80
}

### Z pos cycle
POST http://localhost:5000/my/z_pos_n
Accept: application/json
Content-Type: application/json

{
  "z_pos_start": 80,
  "z_pos_end": 120,
  "n": 2
}

