### Open camera
POST http://localhost:8000/myxthing/open_camera

### Close camera
POST http://localhost:8000/myxthing/close_camera

### Start streaming
POST http://localhost:8000/myxthing/start_stream_camera

### Stop streaming
POST http://localhost:8000/myxthing/stop_stream_camera


### Capture
POST http://localhost:8000/myxthing/capture_camera

### Get xyz
GET http://localhost:8000/myxthing/xyz

### Update xyz
PUT http://localhost:8000/myxthing/xyz

0.01

### Get TD
GET http://localhost:8000/myxthing

### Get invocation by id
GET http://localhost:8000/invocations/60aa8494-914c-4674-b6fe-bf3adabe7e84

### Get Color Filter
GET http://localhost:8000/myxthing/color_filter

### Move Color Filter
POST http://localhost:8000/myxthing/move_color_filter

"Z"

### Get ND Filter Value
GET http://localhost:8000/myxthing/nd_filter

### Move ND Filter
POST http://localhost:8000/myxthing/move_nd_filter

"ND1"

### Get Stage position
GET http://localhost:8000/myxthing/stage

### Move Stage Position Abs
POST http://localhost:8000/myxthing/move_stage_abs

0.4

### Move Stage Position Rel
POST http://localhost:8000/myxthing/move_stage_rel

-0.001

