from typing import Protocol, Any, Callable

class Camera(Protocol):
    def arm(self) -> None:
        ...

    def disarm(self) -> None:
        ...

    def set_exposure_time(self, exposure_time_in_us: float) -> None:
        ...

    def get_exposure_time(self) -> float:
        ...

    def set_gain(self, gain_in_db: float) -> None:
        ...

    def get_gain(self) -> float:
        ...

    def start_streaming(self, frame_handler: Callable[[Any], None]) -> None:
        ...

    def stop_streaming(self) -> None:
        ...

    def is_streaming(self) -> bool:
        ...

    def trigger_and_capture(self, count: int) -> list[Any]:
        ...
